checkra1n: Add instructions for Debian-based distros
cfw-guide/ios.cfw.guide pull request #167
Opened 2022-05-08 04:15 UTC by TheRealKeto

This PR adds specific instructions, provided by the checkra1n team, for Debian-based distros to the Linux section of the checkra1n guide. Considering that this is the method that is recommended by the checkra1n team, there's no reason to not mention this in the guide, considering how much easier it is.

2022-05-08 04:22 UTC, TheMasterOfMike requested changes
I feel like this would overall work better if the following was done:
- Make the first paragraph (two sentences) part of one tip box instead
- Eliminate the last sentence entirely

2022-05-08 18:08 UTC, CFSerena approved these changes

2022-05-08 18:18 UTC, emiyl commented
we could also just use tabs and include these instructions in the guide?

2022-05-08 18:19 UTC, TheMasterOfMike commented
> we could also just use tabs and include these instructions in the guide?

why aren't we using tabs in the first place

2022-05-08 18:46 UTC, emiyl commented
because tabs didn't exist when we wrote it all

2022-05-13 04:05 UTC, TheRealKeto commented
That's a transition that I currently cannot help with; for now, it's best to leave the structure the way it is. I personally don't see other pages being transition to this mechanism, which is why this PR is done the way it is.

2022-05-15 05:58 UTC, merged